### ISSUE TITLE
I hear VSCO changed its code recently. Downloader isn't working :(

### ISSUE THREAD

**Issue by cez2020** [NicholasDawson/VSCO-Downloader#16]
This is what I typed in:

Enter a command: -i some-user
Finding new posts of some-user: 0 posts [00:00, ? posts/s]
Downloading posts of some-user: 0 posts [00:00, ? posts/s]

Clearly the user has photos available in profile but Downloader isn't finding any

**Comment by NicholasDawson** [comment]
Hey cez2020,

You have to use `<username> -i` instead of `-i some-user`

Best,
Nick
